#!/usr/bin/env python
import sys
from optparse import OptionParser, OptionGroup
from sys import stdout, stderr, exit
from subprocess import Popen,call,PIPE

parser = OptionParser(usage='Usage: %prog [options] [input file list]')
parser.add_option('-b','--branch-name',dest='branch_name',
                  help='Branch name to be split',metavar='BRANCH')
parser.add_option('-w','--bin-width',dest='bin_width',
                  help='Width of each bin',metavar='WIDTH')
parser.add_option('-i','--init-val',dest='init_val',
                  help='Initial value of branch_name to start at',metavar='I')
parser.add_option('-n','--n-bins',dest='n_bins',
                  help='Number of bins to split into',metavar='N')
(options,args)=parser.parse_args()
def main():
    branch_name=options.branch_name
    sh_args=''
    bins=int(options.n_bins)
    bin_width=float(options.bin_width)
    init_val=float(options.init_val)
    for i in range(0,bins):
        lo=bin_width*i+init_val
        hi=bin_width*(i+1)+init_val
        key=("%s_%d_%d:"%(branch_name,int(lo*100),int(hi*100))).replace("-","n")
        sh_args+=key+"\"(%s > %.3g) && (%s < %.3g)\" "%(branch_name,lo,
                                                    branch_name,hi)
    for fname in args:
        if fname.split('.')[-1]!='root':
            print "ERROR: This script should only be run on root files"
            exit(1)
        process=Popen("split-tree -i %s -t mini "%(fname) + sh_args,shell=True,stdout=stdout,stderr=stderr)
        process.wait()
if __name__ == "__main__":
   sys.exit(main()) 
